add export function; reorganize imports
neuroinfo-os/BSTIM-Covid19 pull request #17
Opened 2020-10-27 09:05 UTC by kreuzert

export function:
copy files from `_job_/csv/2020_09_11` to `shared_folder/csv/2020_10_06`

This way we will get rid of the offset, without changing anything within the computation

2020-10-27 09:57 UTC, pnieters requested changes
I think you were 1 commit behind -- I added an indicator for 'RKI data above 95th percentile' for unusually high data; useful for plotting. Requires rki data before dataframe construction (108-110), in addition to the extra df column.
Please remerge current file into your version!

2020-10-27 09:58 UTC, pnieters commented on src/results_to_csv.py
> -        rki_data = np.append(target.loc[:, county_id].values, np.repeat(np.nan, 5))
Need this calculated before df

2020-10-27 09:58 UTC, pnieters commented on src/results_to_csv.py
> -            'is_high': np.less(prediction_q95_trend.loc[:,county_id].values, rki_data)},
removed on purpose?

2020-10-27 11:51 UTC, kreuzert commented
Used the code on JUSUF at $PROJECT_.../autostart_csv/BSTIM-Covid19 as base. I assume that code was not up to date

2020-10-29 06:10 UTC, merged

2020-10-29 06:10 UTC, pnieters commented
Cheers!